### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by Entkenntnis** [botsk/BrainFuck-Interpreter#2]
https://brainfuck-visualizer.herokuapp.com/ is not reachable at the moment

**Comment by usaikiran** [comment]
Temporarily hosted at https://brainfuck-vm.netlify.app/

**Comment by Entkenntnis** [comment]
thank you

**Comment by usaikiran** [comment]
@Entkenntnis Permenantly hosted at https://brainfuck-visualizer.xyz/. Thanks for reporting the issue.
